name: Mediawiki Job Runner Image Build

on:
  push:
    branches:
      - 'jobrunner'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: starcitizentools/mediawiki:jobrunner-lastest,starcitizentools/mediawiki:jobrunner-v2.0.0