name: Mediawiki Image Build

on:
  push:
    branches:
      - 'mediawiki-1-39'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: starcitizentools/mediawiki:139-latest,starcitizentools/mediawiki:139-v2.1.3
